#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
source "$ROOT_DIR/scripts/profile/env.sh"

JWT_SECRET="${JWT_SECRET:-local_acceptance_jwt_secret}"
COOKIE_SECRET="${COOKIE_SECRET:-local_acceptance_cookie_secret}"
MANUAL_WEBHOOK_SECRET="${MANUAL_WEBHOOK_SECRET:-local_acceptance_manual_webhook_secret}"
CREDENTIAL_ENCRYPTION_KEY="${CREDENTIAL_ENCRYPTION_KEY:-0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef}"
CREDENTIAL_ENCRYPTION_KEY_PREVIOUS="${CREDENTIAL_ENCRYPTION_KEY_PREVIOUS:-}"
DELIVERY_ENCRYPTION_KEY="${DELIVERY_ENCRYPTION_KEY:-$CREDENTIAL_ENCRYPTION_KEY}"
DELIVERY_ENCRYPTION_KEY_PREVIOUS="${DELIVERY_ENCRYPTION_KEY_PREVIOUS:-}"
SITE_ID="${SITE_ID:-site-1}"
SITE_ENV="${SITE_ENV:-development}"
NEXT_PUBLIC_SITE_ID="${NEXT_PUBLIC_SITE_ID:-$SITE_ID}"
NEXT_PUBLIC_SITE_ENV="${NEXT_PUBLIC_SITE_ENV:-$SITE_ENV}"
SITE_PROFILES_ROOT="$(resolve_site_profiles_root "$ROOT_DIR" "${SITE_PROFILES_ROOT:-}")"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-/tmp/store-local-acceptance-config}"

validate_site_profile "$SITE_ID" "$SITE_ENV" "$SITE_PROFILES_ROOT"
pnpm services:up
mkdir -p "$XDG_CONFIG_HOME"
XDG_CONFIG_HOME="$XDG_CONFIG_HOME" \
JWT_SECRET="$JWT_SECRET" \
COOKIE_SECRET="$COOKIE_SECRET" \
MANUAL_WEBHOOK_SECRET="$MANUAL_WEBHOOK_SECRET" \
CREDENTIAL_ENCRYPTION_KEY="$CREDENTIAL_ENCRYPTION_KEY" \
CREDENTIAL_ENCRYPTION_KEY_PREVIOUS="$CREDENTIAL_ENCRYPTION_KEY_PREVIOUS" \
DELIVERY_ENCRYPTION_KEY="$DELIVERY_ENCRYPTION_KEY" \
DELIVERY_ENCRYPTION_KEY_PREVIOUS="$DELIVERY_ENCRYPTION_KEY_PREVIOUS" \
SITE_ID="$SITE_ID" \
SITE_ENV="$SITE_ENV" \
SITE_PROFILES_ROOT="$SITE_PROFILES_ROOT" \
  pnpm --dir apps/backend exec medusa db:migrate
XDG_CONFIG_HOME="$XDG_CONFIG_HOME" \
JWT_SECRET="$JWT_SECRET" \
COOKIE_SECRET="$COOKIE_SECRET" \
MANUAL_WEBHOOK_SECRET="$MANUAL_WEBHOOK_SECRET" \
CREDENTIAL_ENCRYPTION_KEY="$CREDENTIAL_ENCRYPTION_KEY" \
CREDENTIAL_ENCRYPTION_KEY_PREVIOUS="$CREDENTIAL_ENCRYPTION_KEY_PREVIOUS" \
DELIVERY_ENCRYPTION_KEY="$DELIVERY_ENCRYPTION_KEY" \
DELIVERY_ENCRYPTION_KEY_PREVIOUS="$DELIVERY_ENCRYPTION_KEY_PREVIOUS" \
SITE_ID="$SITE_ID" \
SITE_ENV="$SITE_ENV" \
SITE_PROFILES_ROOT="$SITE_PROFILES_ROOT" \
  pnpm --dir apps/backend build
SITE_ID="$SITE_ID" \
SITE_ENV="$SITE_ENV" \
NEXT_PUBLIC_SITE_ID="$NEXT_PUBLIC_SITE_ID" \
NEXT_PUBLIC_SITE_ENV="$NEXT_PUBLIC_SITE_ENV" \
SITE_PROFILES_ROOT="$SITE_PROFILES_ROOT" \
  pnpm --dir apps/storefront lint
SITE_ID="$SITE_ID" \
SITE_ENV="$SITE_ENV" \
NEXT_PUBLIC_SITE_ID="$NEXT_PUBLIC_SITE_ID" \
NEXT_PUBLIC_SITE_ENV="$NEXT_PUBLIC_SITE_ENV" \
SITE_PROFILES_ROOT="$SITE_PROFILES_ROOT" \
  pnpm --dir apps/storefront build

echo "local-acceptance: build-level checks passed"
